name: example-install-command
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Cypress v9 and lower ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

  install-command:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Custom Yarn command
        uses: ./
        with:
          working-directory: examples/v9/install-command
          # https://classic.yarnpkg.com/en/docs/cli/install
          install-command: yarn --frozen-lockfile --silent

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Cypress v10 and higher ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

  install-command-v10:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Custom Yarn command
        uses: ./
        with:
          working-directory: examples/v10/install-command
          # https://classic.yarnpkg.com/en/docs/cli/install
          install-command: yarn --frozen-lockfile --silent
