name: example-yarn-classic
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  yarn-classic:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test with Yarn Classic
        uses: ./ # if copying, replace with cypress-io/github-action@v6
        with:
          working-directory: examples/yarn-classic
