name: example-chrome
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:

  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress info
        uses: ./
        with:
          # just for full picture after installing Cypress
          # print information about detected browsers, etc
          # see https://on.cypress.io/command-line#cypress-info
          build: npx cypress info
          working-directory: examples/browser

      - name: Chrome
        uses: ./
        with:
          working-directory: examples/browser
          browser: chrome

      - uses: actions/upload-artifact@v3
        with:
          name: screenshots-in-chrome
          path: examples/browser/cypress/screenshots

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: examples/browser

      - name: Chrome headless
        uses: ./
        with:
          working-directory: examples/browser
          browser: chrome
          headed: false

      - uses: actions/upload-artifact@v3
        with:
          name: screenshots-in-headless-chrome
          path: examples/browser/cypress/screenshots

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: examples/browser
