name: example-start
# In the example jobs, the action is called with
# uses: ./
# which runs the action code from the current branch.
# If you copy this workflow to another repo, replace the line with
# uses: cypress-io/github-action@v6
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

env:
  # Disable update-check called by serve through start or start2 script
  # works around issue when more than one instance of serve is started
  # See PR https://github.com/vercel/serve/pull/457
  NO_UPDATE_CHECK: 1

jobs:
  start:
    # example with web application build,
    # server start and waiting for the server
    # to respond before running tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/start
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'

  start-multiple:
    # example with web application build
    # and several services to start
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/start
          build: npm run build
          # single start command per line
          start: |
            npm start
            npm run start2
          wait-on: 'http://localhost:8000'
          config: 'baseUrl=http://localhost:8000'

  start-multiple-commas:
    # example with web application build
    # and several services to start
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/start
          build: npm run build
          # use commas to separate the commands
          start: npm start, npm run start2
          wait-on: 'http://localhost:8000'
          config: 'baseUrl=http://localhost:8000'
