name: example-debug
on: push
jobs:
  nightly:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress debug logs ğŸ“
        uses: ./
        env:
          DEBUG: '@cypress/github-action'
        with:
          working-directory: examples/basic
