name: example-start-and-yarn-workspaces
on: [push]
jobs:
  single:
    # the example has Yarn workspace in its "root" folder
    # examples/start-and-yarn-workspaces
    # and tests in a subfolder like "workspace-1"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Tests
        uses: ./
        with:
          working-directory: examples/start-and-yarn-workspaces/workspace-1
          build: yarn run build
          start: yarn start
          wait-on: 'http://localhost:5000'

  multiple:
    # example with web application build,
    # server start and waiting for the server
    # to respond before running tests
    # in each Yarn workspaces subfolder
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        cypress:
          - working_directory: examples/start-and-yarn-workspaces/workspace-1
          - working_directory: examples/start-and-yarn-workspaces/workspace-2
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress tests
        uses: ./
        with:
          working-directory: ${{ matrix.cypress.working_directory }}
          build: yarn run build
          start: yarn start
          wait-on: 'http://localhost:5000'
