name: example-node-versions
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    # let's make sure Cypress works on several versions of Node
    strategy:
      matrix:
        node: [8.12, 10, 12]
    name: E2E on Node v${{ matrix.node }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
      - run: npm -v

      - name: Checkout
        uses: actions/checkout@v2

      # Hmm, should we rebuild the "dist" before using the action?

      - uses: ./
        with:
          working-directory: examples/node-versions
