name: example-custom-command
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Cypress v9 and lower ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

  start:
    # example where instead of forming the default "cypress run ..."
    # the user can specify their own command
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v3

      - name: Custom tests ðŸ§ª
        uses: ./
        with:
          command: npm run custom-test
          working-directory: examples/v9/custom-command

      - name: Show saved file ðŸ–¨
        run: cat examples/v9/custom-command/results.json

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Cypress v10 and higher ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

  start-v10:
    # example where instead of forming the default "cypress run ..."
    # the user can specify their own command
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v3

      - name: Custom tests ðŸ§ª
        uses: ./
        with:
          command: npm run custom-test
          working-directory: examples/v10/custom-command

      - name: Show saved file ðŸ–¨
        run: cat examples/v10/custom-command/results.json