name: example-custom-command
on: [push]
jobs:
  start:
    # example where instead of forming the default "cypress run ..."
    # the user can specify their own command
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v1

      - name: Custom tests ðŸ§ª
        uses: ./
        with:
          command: npm run custom-test
          working-directory: examples/custom-command

      - name: Show saved file ðŸ–¨
        run: cat examples/custom-command/results.json
