name: example-yarn-modern
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  yarn-modern:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: corepack enable yarn # experimental - see https://nodejs.org/docs/latest/api/corepack.html
      - name: Set up Yarn cache
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: yarn
          cache-dependency-path: examples/yarn-modern/yarn.lock
      - name: Custom Yarn command
        uses: ./
        with:
          working-directory: examples/yarn-modern
          # https://yarnpkg.com/cli/install
          install-command: yarn install
