name: example-node-versions
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Cypress v9 and lower ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

  cypress-run:
    runs-on: ubuntu-20.04
    # let's make sure Cypress works on several versions of Node
    strategy:
      matrix:
        node: [14, 16, 18]
    name: Cypress v9 E2E on Node v${{ matrix.node }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
      - run: npm -v

      - name: Checkout
        uses: actions/checkout@v3

      # Hmm, should we rebuild the "dist" before using the action?

      - uses: ./
        with:
          working-directory: examples/v9/node-versions

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Cypress v10 and higher ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

  cypress-run-v10:
    runs-on: ubuntu-20.04
    # let's make sure Cypress works on several versions of Node
    strategy:
      matrix:
        node: [14, 16, 18]
    name: Cypress v10 E2E on Node v${{ matrix.node }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
      - run: npm -v

      - name: Checkout
        uses: actions/checkout@v3

      # Hmm, should we rebuild the "dist" before using the action?

      - uses: ./
        with:
          working-directory: examples/v10/node-versions
