name: example-custom-command
# example using the command parameter
# this allows any cli command to be run
# the command parameter causes other action parameters that would be passed to Cypress
# to be ignored and so it should not be used with these other parameters
# for example, browsers, config, record, parallel, spec, etc would be ignored
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Custom tests
        uses: ./ # if copying, replace with cypress-io/github-action@v6
        with:
          command: npm run custom-test
          working-directory: examples/custom-command

      - name: Show saved file
        run: cat examples/custom-command/results.json
