name: example-yarn-modern
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  yarn-modern:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable Corepack # see https://yarnpkg.com/getting-started/install
        run: |
          npm install -g corepack
          corepack enable yarn
      - name: Set up Yarn cache
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: yarn
          cache-dependency-path: examples/yarn-modern/yarn.lock
      - name: Reinstall Corepack # actions/setup-node may have replaced Corepack with an older version
        run: |
          npm install -g corepack
          corepack enable yarn
      - name: Custom Yarn command
        uses: ./ # if copying, replace with cypress-io/github-action@v6
        with:
          working-directory: examples/yarn-modern
          # https://yarnpkg.com/cli/install
          install-command: yarn install
