name: example-docker
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  docker-browsers:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, edge, electron, firefox]
    # Cypress Docker image documentation on https://github.com/cypress-io/cypress-docker-images
    # Available cypress/browsers tags listed on https://hub.docker.com/r/cypress/browsers/tags
    container:
      image: cypress/browsers:24.13.0
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Cypress tests
        uses: ./ # if copying, replace with cypress-io/github-action@v6
        with:
          working-directory: examples/basic
          browser: ${{ matrix.browser }}
