name: example-install-command
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  install-command:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Custom Yarn command
        uses: ./ # if copying, replace with cypress-io/github-action@v6
        with:
          working-directory: examples/install-command
          # https://classic.yarnpkg.com/en/docs/cli/install
          install-command: yarn --frozen-lockfile --silent
