name: example-start-and-yarn-workspaces
# In the example jobs, the action is called with
# uses: ./
# which runs the action code from the current branch.
# If you copy this workflow to another repo, replace the line with
# uses: cypress-io/github-action@v6
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  single:
    # the example has Yarn workspace in its "root" folder
    # examples/start-and-yarn-workspaces
    # and tests in a subfolder like "workspace-1"
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Single
        uses: ./
        with:
          working-directory: examples/start-and-yarn-workspaces/workspace-1
          build: yarn run build
          start: yarn start
          wait-on: 'http://localhost:5000'

  multiple:
    # example with web application build,
    # server start and waiting for the server
    # to respond before running tests
    # in each Yarn workspaces subfolder
    runs-on: ubuntu-24.04
    strategy:
      # fail-fast: false allows tests for both workspaces to run even if one fails
      fail-fast: false
      matrix:
        cypress:
          - working_directory: examples/start-and-yarn-workspaces/workspace-1
          - working_directory: examples/start-and-yarn-workspaces/workspace-2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        uses: ./
        with:
          working-directory: ${{ matrix.cypress.working_directory }}
          build: yarn run build
          start: yarn start
          wait-on: 'http://localhost:5000'
