name: example-chrome
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress info
        uses: ./
        with:
          # just for full picture after installing Cypress
          # print information about detected browsers, etc
          # see https://on.cypress.io/command-line#cypress-info
          build: npx cypress info
          working-directory: examples/chrome

      - name: Electron
        uses: ./
        with:
          working-directory: examples/chrome

      # store screenshot captured during the test
      - uses: actions/upload-artifact@v1
        with:
          name: screenshots-in-electron
          path: examples/chrome/cypress/screenshots

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: examples/chrome

      - name: Chrome
        uses: ./
        with:
          working-directory: examples/chrome
          browser: chrome

      - uses: actions/upload-artifact@v1
        with:
          name: screenshots-in-chrome
          path: examples/chrome/cypress/screenshots

      - uses: actions/upload-artifact@v1
        with:
          name: video-in-chrome
          path: examples/chrome/cypress/videos

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: examples/chrome

      # I wonder if GH Actions VM includes any of the tools that
      # can tell us the resolution of a video file
      - run: ffprobe cypress/videos/*.mp4 || true
      - run: mplayer -really-quiet -ao null -vo null -identify -frames 0 cypress/videos/*.mp4 || true

      - name: Chrome headless
        uses: ./
        with:
          working-directory: examples/chrome
          browser: chrome
          headless: true

      - uses: actions/upload-artifact@v1
        with:
          name: screenshots-in-headless-chrome
          path: examples/chrome/cypress/screenshots

      - uses: actions/upload-artifact@v1
        with:
          name: video-in-headless-chrome
          path: examples/chrome/cypress/videos

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: examples/chrome
