name: main
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    name: Build and test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          # Action runs: using: node20 as defined in
          # https://github.com/cypress-io/github-action/blob/master/action.yml
          # Node.js minor version is aligned to
          # https://github.com/actions/runner/blob/main/src/Misc/externals.sh
          node-version: 20.19.4
      - run: npm ci
      # Core action code
      - run: npm run format # Prettier formats core action code
      - run: npm run build # builds core action code into dist/
      # All repo
      - run: npm run lint # ESLint
      - run: npm run format:all:check # Prettier formatting check

  release:
    runs-on: ubuntu-24.04
    name: release
    needs: [build-and-test]
    # only release from the master branch
    # in parent repository, not in a fork
    if: (github.ref == 'refs/heads/master') &&
      (github.repository == 'cypress-io/github-action')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm ci
      # https://github.com/cycjimmy/semantic-release-action
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          # https://github.com/semantic-release/semantic-release
          semantic_version: 24.2.3
          branches: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push updates to branch for major version
        # if there is a new version published, let's say v1.2.3
        # then this step will update branch "v1" to this commit
        # https://github.com/cypress-io/github-action/branches
        if: steps.semantic.outputs.new_release_published == 'true'
        run: 'git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/v${{steps.semantic.outputs.new_release_major_version}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
